config/routes.rb
Gestionclub::Application.routes.draw do
  post "pagos/create"
  post "pagos/delete"
  post "pagos/update"

  get "caja/index"
  get "caja/cobrar_por_socio"
  get "caja/cobrar_a_socio/:socio_id" => "caja#cobrar_a_socio", as: :caja_cobrar_a_socio

  get "web/redirigir"

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :socios

  resources :periodos
  get 'periodos/:id/generar_deuda' => 'periodos#generar_deuda', as: :generar_deuda

  resources :categorias

  root 'web#redirigir'

end

app/models/periodo.rb
class Periodo < ActiveRecord::Base

  has_many :costo_por_categorias
  has_many :deudas
  has_many :categorias, through: :costo_por_categorias

  accepts_nested_attributes_for :costo_por_categorias

  before_create :init

  def init
    Categoria.all.each do |cat|
      costo_por_categorias.build categoria: cat, costo: 0
    end
  end

  def generar_deuda_a_socios_activos
    #obtener todos los socios activos
    Socio.activos.each do |socio|
      socio.generar_deuda self
    end
  end

end

app/controllers/periodos_controller.rb
class PeriodosController < InheritedResources::Base
  before_filter :authenticate_user!, :authorize_user!


  def generar_deuda
    @periodo = Periodo.find params[:id]
    @periodo.generar_deuda_a_socios_activos
    flash[:notice] = "Generadas deudas a socios para el periodo '"+@periodo.nombre+"'. Total generadas: "+ Deuda.where(periodo: @periodo).count.to_s
    redirect_to periodos_path
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def permitted_params
      params.permit(:periodo => [:nombre, :fecha_vencimiento, :costo_por_categorias, costo_por_categorias_attributes: [:id, :categoria_id, :costo]])
    end

    def authorize_user!
      authorize Periodo
    end
end

app/views/periodos/_form.html.erb
<%= simple_form_for @periodo, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nombre %>
  <%= f.input :fecha_vencimiento %>
  <%= f.simple_fields_for :costo_por_categorias do |c| %>
    <%= c.association :categoria, input_html: {disabled: "disabled"} %>
    <%= c.input :costo %>
  <% end %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                periodos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/periodos/edit.html.erb
<%- model_class = Periodo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/periodos/index.html.erb
<%- model_class = Periodo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= "Generado" %></th>
      <th><%= model_class.human_attribute_name(:fecha_vencimiento) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @periodos.each do |periodo| %>
      <tr>
        <td><%= periodo.id %></td>
        <td><%= link_to periodo.nombre, periodo_path(periodo) %></td>
        <td><%= l periodo.created_at.to_date %></td>
        <td><%= l periodo.fecha_vencimiento %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_periodo_path(periodo), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      periodo_path(periodo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_periodo_path,
            :class => 'btn btn-primary' %>

app/views/periodos/new.html.erb
<%- model_class = Periodo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/periodos/show.html.erb
<%- model_class = Periodo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @periodo.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fecha_vencimiento) %>:</strong></dt>
  <dd><%= l @periodo.fecha_vencimiento %></dd>
</dl>
<br>
<br>
<h4> Costos de la cuota </h4>

<table class="table" style="width: 300px;">
  <thead>
    <tr>
      <th>Categoria</th>
      <th>Costo</th>
    </th>
  </thead>
  <tbody>
    <% @periodo.costo_por_categorias.each do |costo_por_categoria| %>
    <tr>
      <td><%= costo_por_categoria.categoria.nombre %></td>
      <td><%= costo_por_categoria.costo.to_s + " $" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to "Liquidar periodo", generar_deuda_path(@periodo), class: "btn" %>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              periodos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_periodo_path(@periodo), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              periodo_path(@periodo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>