config/routes.rb
Gestionclub::Application.routes.draw do
  post "pagos/create"
  post "pagos/delete"
  post "pagos/update"

  get "caja/index"
  get "caja/cobrar_por_socio"
  get "caja/cobrar_a_socio/:socio_id" => "caja#cobrar_a_socio", as: :caja_cobrar_a_socio

  get "web/redirigir"

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :socios

  resources :periodos
  get 'periodos/:id/generar_deuda' => 'periodos#generar_deuda', as: :generar_deuda

  resources :categorias

  root 'web#redirigir'

end

app/controllers/caja_controller.rb
class CajaController < ApplicationController
  layout "caja"
  before_filter :authenticate_user!, :authorize_user!

  def index
  end

  def cobrar_por_socio
    @q = Socio.search(params[:q])
    @socios = @q.result.activos
  end

  def cobrar_a_socio
    @socio = Socio.find params[:socio_id]
    @deudas = @socio.deudas.impagas
    @pago = Pago.new
  end

  private
    def authorize_user!
      authorize CajaController
    end
end

app/views/caja/_modal_pago.html.slim
div.modal.hide.fade id=(deuda.id)
  = form_for @pago, url: pagos_create_path do |f|
    .modal-header
      button.close type="button" data-dismiss="modal" aria-hidden="true" X
      h3 Realizar Pago
    .modal-body
      p = "Deuda: " + deuda.concepto
      = f.text_field :deuda_id, type: "hidden", value: deuda.id
      = f.label "Ingrese monto"
      = f.text_field :monto
    .modal-footer
      = link_to "Cancelar","#", class: "btn"
      = f.submit "Aceptar", class: "btn btn-primary"

app/views/caja/cobrar_a_socio.html.slim
- @deudas.each do |deuda|
  = render partial: "modal_pago", locals: {deuda: deuda}

.page-header
  h1 Cobro por socio

.container-fluid
  .span12
    == "<b>Socio: </b>"+ @socio.nombre
    hr
    table.table.table-striped
      thead
        tr
          th Fecha
          th Concepto
          th Pendiente
          th Vencimiento
      tbody
        - @deudas.each do |deuda|
          tr class=('error' if deuda.vencida?)
            td = formatear_fecha deuda.created_at
            td = link_to deuda.concepto, "#"+deuda.id.to_s, role: "button", data: {toggle: "modal"}
            td = deuda.monto_pendiente
            td = formatear_fecha deuda.fecha_vencimiento

app/views/caja/cobrar_por_socio.html.slim
.page-header
  h1 Cobrar deudas por socio

.container-fluid
  .span12
    = render partial: "socios/search", locals: {url: caja_cobrar_por_socio_path}
    table.table.table-striped
      thead
        tr
          th Nombre
          th Activo
          th Al dia
          th Deuda total
      tbody
        - @socios.each do |socio|
          tr
            td = link_to socio.nombre, caja_cobrar_a_socio_path(socio.id)
            td = yes_no_icon socio.activo
            td = yes_no_icon socio.al_dia?
            td = socio.saldo_cuenta

app/views/caja/index.html.slim
h1 Panel de cajero
hr
= image_tag "cajafuerte.png", size: "300x300" 