config/routes.rb
Gestionclub::Application.routes.draw do
  post "pagos/create"
  post "pagos/delete"
  post "pagos/update"

  get "caja/index"
  get "caja/cobrar_por_socio"
  get "caja/cobrar_a_socio/:socio_id" => "caja#cobrar_a_socio", as: :caja_cobrar_a_socio

  get "web/redirigir"

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :socios

  resources :periodos
  get 'periodos/:id/generar_deuda' => 'periodos#generar_deuda', as: :generar_deuda

  resources :categorias

  root 'web#redirigir'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError do |exception|
    flash[:error] = "No estas autorizado a ver este contenido"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatear_fecha fecha
    l fecha.to_date
  end

  def yes_no_icon(bool)
    if bool
       '<i class="icon-ok"></i>'.html_safe
    else
       '<i class="icon-remove"></i>'.html_safe
    end
  end
end

app/views/application/_footer.html.erb
<div class="container-fluid">
  <footer>
    &copy; Gestion Club 2014
  </footer>
</div>

app/views/application/_navbar_administrador.html.erb
<div class="container-fluid nav-collapse">
  <ul class="nav">
    <li><%= link_to "Socios", socios_path %></li>
    <li><%= link_to "Periodos", periodos_path  %></li>
    <li><%= link_to "Categorias", categorias_path  %></li>
    <li><%= link_to "Salir", destroy_user_session_path, method: :delete  %></li>
  </ul>
</div><!--/.nav-collapse -->

app/views/application/_navbar_cajero.html.slim
.container-fluid.nav-collapse
  ul.nav
    li.dropdown
      a.dropdown-toggle data-toggle="dropdown" href=""
        |Cobrar
        b.caret
      ul.dropdown-menu role="menu" aria-labelledby="dLabel"
        li = link_to "Ingresar por deuda", "#"
        li = link_to "Buscar por socio", caja_cobrar_por_socio_path
    li
      =link_to "Salir", destroy_user_session_path, method: :delete